/**
 * Maps topic keywords to their corresponding brief note paths.
 * Shared between get_brief and get_context tools.
 */
export const BRIEF_MAP: Record<string, string> = {
  retrieval: "02-Retrieval/brief-hybrid-retrieval.md",
  hybrid: "02-Retrieval/brief-hybrid-retrieval.md",
  rrf: "02-Retrieval/brief-hybrid-retrieval.md",
  fusion: "02-Retrieval/brief-hybrid-retrieval.md",
  routing: "02-Retrieval/brief-brief-routing.md",
  abstention: "02-Retrieval/brief-brief-routing.md",
  embeddings: "02-Retrieval/brief-embedding-index.md",
  semantic: "02-Retrieval/brief-embedding-index.md",
  search: "02-Retrieval/brief-search-index.md",
  keyword: "02-Retrieval/brief-search-index.md",
  capture: "03-Lifecycle/brief-session-capture.md",
  sessions: "03-Lifecycle/brief-session-capture.md",
  redaction: "03-Lifecycle/brief-session-capture.md",
  digests: "03-Lifecycle/brief-digests-archive.md",
  archive: "03-Lifecycle/brief-digests-archive.md",
  proposals: "03-Lifecycle/brief-brief-proposals.md",
  weekly: "03-Lifecycle/brief-weekly-loop.md",
  autonomous: "03-Lifecycle/brief-weekly-loop.md",
  transport: "01-Architecture/brief-mcp-transport.md",
  mcp: "01-Architecture/brief-mcp-transport.md",
  auth: "01-Architecture/brief-mcp-transport.md",
  structure: "01-Architecture/brief-vault-structure.md",
  frontmatter: "01-Architecture/brief-vault-structure.md",
  pathsafety: "01-Architecture/brief-path-safety.md",
  traversal: "01-Architecture/brief-path-safety.md",
  vaults: "04-Operations/brief-multi-vault.md",
  onboarding: "04-Operations/brief-onboarding.md",
  bootstrap: "04-Operations/brief-onboarding.md",
  doctor: "04-Operations/brief-observability.md",
  observability: "04-Operations/brief-observability.md",
  eval: "04-Operations/brief-eval-harness.md",
  coffee: "05-Kitchen/brief-coffee-roasting.md",
  sourdough: "05-Kitchen/brief-sourdough.md",
  drivetrain: "06-Cycling/brief-bike-maintenance.md",
};
