// `00-Index/index.md`: one line per curated note, grouped by top-level folder,
// so an agent (or a human) can read the index first and drill in, with no
// search call. Regenerated, never hand-edited; the log records each rebuild.

import { isRawSession } from "../retrieval/hybrid.js";

export interface IndexableNote {
  path: string;
  title: string;
  tags: string[];
  content: string;
}

export function summaryLine(content: string, max = 120): string {
  const tldr = content.match(/^>\s*TL;DR[:\s]+(.+)$/m);
  let s = tldr ? tldr[1] : "";
  if (!s) {
    for (const block of content.split(/\n\s*\n/)) {
      const t = block.trim();
      if (!t || t.startsWith("#") || t.startsWith("---") || t.startsWith("```") || t.startsWith("|")) continue;
      s = t.replace(/\s+/g, " ");
      break;
    }
  }
  s = s.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_m, a, b) => b ?? a);
  return s.length > max ? s.slice(0, max - 1).trimEnd() + "…" : s;
}

export function buildIndexMarkdown(notes: IndexableNote[], opts: { title?: string; date?: string } = {}): string {
  const date = opts.date ?? new Date().toISOString().slice(0, 10);
  const curated = notes.filter(
    (n) => !isRawSession(n.path) && !n.path.startsWith("00-Index/") && !n.path.startsWith("proposals/") && !n.path.startsWith("sessions/digests/_runs/")
  );
  const groups = new Map<string, IndexableNote[]>();
  for (const n of curated) {
    const top = n.path.includes("/") ? n.path.slice(0, n.path.indexOf("/")) : "(root)";
    const key = n.path.startsWith("sessions/digests/") ? "sessions/digests" : top;
    const arr = groups.get(key) ?? [];
    arr.push(n);
    groups.set(key, arr);
  }
  const sections = [...groups.keys()].sort().map((folder) => {
    const items = groups.get(folder)!.sort((a, b) => a.path.localeCompare(b.path));
    const lines = items.map((n) => {
      const base = n.path.split("/").pop()!.replace(/\.md$/i, "");
      const kind = n.tags.find((t) => t.startsWith("type/"))?.slice(5);
      const s = summaryLine(n.content);
      return `- [[${base}|${n.title}]]${kind ? ` \`${kind}\`` : ""}${s ? `: ${s}` : ""}`;
    });
    return `## ${folder}\n\n${lines.join("\n")}`;
  });
  return [
    "---",
    `title: ${opts.title ?? "Index"}`,
    "tags:",
    "  - type/index",
    `updated: '${date}'`,
    "---",
    "",
    `# ${opts.title ?? "Index"}`,
    "",
    `${curated.length} curated notes. Regenerated by \`accretion index\`; read this first, then open the note.`,
    "",
    ...sections.flatMap((s) => [s, ""]),
  ].join("\n");
}
